config/routes.rb
Rails.application.routes.draw do
  # [X] - As a user, I can see all my lists
  # [X] - As a user, I can create a list
  # [X] - As a user, I can see the details of a list
  # [ ] - As a user, I can bookmark a movie inside a list
  # [ ] - As a user, I can destroy a bookmark
  root to: "lists#index"
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # associations
  belongs_to :movie # creates a method => bookmark.movie
  belongs_to :list # creates a method => bookmark.list
  # validations
  # validates :column_name, actual_validation
  validates :movie, uniqueness: { scope: :list }
  # validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  # associations
  has_many :bookmarks, dependent: :destroy # creates a method => list.bookmarks
  has_many :movies, through: :bookmarks # creates a method => list.movies
  # validations
  validates :name, presence: true, uniqueness: true
  # images iploading part
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # 'lists/1/bookmarks/new'
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.order(title: :asc)
  end

  # this can't be accessed by a url. a form will post data here
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # '/lists'
  def index
    @lists = List.all
  end

  # '/lists/1'
  def show
    @list = List.find(params[:id])
  end

  # '/lists/new'
  def new
    # for our form builder helper
    @list = List.new
  end

  # this can't be accessed by a url. a form will post data here
  def create
    @list = List.new(list_params)
    if @list.save
      # makes a request to another controller action
      redirect_to list_path(@list)
    else
      # show some html / aka the form
      # redirect_to new_list_path
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    # white listing the information that came from the form
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a Movie</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: @movies %>
    <%= f.submit class: 'btn btn-dark mt-3' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Rails Watch List">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-4">

  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">Movie Lists</h1>

    <%= link_to new_list_path, class: "btn btn-dark" do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>

  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class: 'text-white text-decoration-none' do %>
        <div class="card-category"
             style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
             url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : 'https://happiclap.com/wp-content/uploads/2019/06/Everyday-Clapboard-1.jpg' %>)">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<div class="container mt-5">
  <h1>Create a List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-dark mt-3' %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container mt-5">

  <div class="d-flex justify-content-between align-items-center mb-4">

    <!-- Esquerda -->
    <%= link_to lists_path, class: "btn btn-dark" do %>
      <i class="fa-solid fa-house"></i>
    <% end %>

    <!-- Centro -->
    <h1 class="mb-0"><%= @list.name %></h1>

    <!-- Direita -->
    <%= link_to new_list_bookmark_path(@list), class: "btn btn-dark" do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>

  </div>

  <div class="cards mb-5">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card" style="width: 18rem; border-radius: 1rem;">
        <%= image_tag bookmark.movie.poster_url, alt: "text" %>
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.comment %></p>
        </div>
      </div>
    <% end %>
  </div>
<%= link_to "Delete",
            list_path(@list),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "btn btn-dark" %>
</div>